### ISSUE TITLE
code callouts?

### ISSUE THREAD

**Issue by colemickens** [Aloso/unidoc#3]
asciidoc code callouts are my #1 missing feature from basically everything that is not asciidoc. Is it on the roadmap at all?

**Comment by Aloso** [comment]
It's currently not planned. If you look in the git history, you'll see that there wasn't any activity in recent years. This is a personal project, which I think is really fun, but I'm not sure if I want to maintain it and implement the remaining features; especially since as far as I know, nobody uses it. I have a job now (as opposed to when I started this project) and I don't have unlimited free time to work on open-source.

If you create a pull request, I'd be happy to merge it. Also, please check out [this issue](https://github.com/Aloso/unidok/issues/4).

**Comment by colemickens** [comment]
Ah, I'm sorry, I must've gotten carried away looking at interesting asciidoc-adjacent repos and/or got swept up by the polish of the website. Unfortunately I'm mostly just looking for a Rust-powered markup-y language with code-callouts, not a particular interest or enough depth to really help anyway.

That all said, thanks for your efforts in the area and the answer!

(I'm going to close this on the assumption that it's not the in the roadmap even if you were full steam ahead on it)
